name: event_reminder_flutter
description: A Flutter app to manage and track scheduled events with reminders.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.18.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Your custom icon path
